micronaut:
  application:
    name: starter
datasources:
  default:
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Root1234&'
    schema-generate: CREATE_DROP
    dialect: MYSQL
